development:
  facebook:
    omniauth_provider_key: 635910369934582
    omniauth_provider_secret: db50e2378a3db822fa5da784af079b9c
  twitter:
    omniauth_provider_key: Q8ycEXDJQvjGYJUyH4rlhadXB
    omniauth_provider_secret: I9ZbU2G7yBg3H8eOUMi4GtBVCyFHbjOpZCM3jCJxH27Wm4tpI0
  domain_name: localhost
  secret_key_base: 11093bea2f34525a321418196222971af39c6a6d90c5853989c425e08e12f9b20e280c944f25eba200e5283e84e24720e2b636c4da0cd5fe378651be19d4a1f3

test:
  secret_key_base: cdcea0f182186b7cc37f654a2035d031a6932d4a79a0d7af788f0141498bb1c7dae9ea17aff759c6e404c014ad19b3d0e09607a40cbfc2a4fc212dd5bc557fa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook:
    omniauth_provider_key: <%= ENV["FACEBOOK_OMNIAUTH_PROVIDER_KEY"] %>
    omniauth_provider_secret: <%= ENV["FACEBOOK_OMNIAUTH_PROVIDER_SECRET"] %>
  twitter:
    omniauth_provider_key: <%= ENV["TWITTER_OMNIAUTH_PROVIDER_KEY"] %>
    omniauth_provider_secret: <%= ENV["TWITTER_OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>